"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

[custom.update]
when = "/usr/bin/rpm-ostree status --json | /usr/bin/jq -e \".deployments[0].booted == false\" > /dev/null;"
command = "echo \"New deployment staged\""
symbol = "!"
format = " $symbol [($output)]($style) "
style = "italic green"
